version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nanny_backend
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8002"]

  db:
    restart: always
    image: postgres:latest  # or specify a specific version, e.g., postgres:13
    container_name: nanny_backend_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
