# Generated by Django 4.2.6 on 2023-10-14 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('country', models.CharField(choices=[('CA', 'Canada'), ('CN', 'China'), ('IN', 'India'), ('US', 'United States'), ('ID', 'Indonesia'), ('PK', 'Pakistan'), ('BR', 'Brazil'), ('NG', 'Nigeria'), ('BD', 'Bangladesh'), ('RU', 'Russia'), ('MX', 'Mexico'), ('JP', 'Japan'), ('PH', 'Philippines'), ('ET', 'Ethiopia'), ('EG', 'Egypt'), ('VN', 'Vietnam'), ('CD', 'DR Congo'), ('TR', 'Turkey'), ('IR', 'Iran'), ('DE', 'Germany'), ('FR', 'France'), ('GB', 'United Kingdom'), ('TH', 'Thailand'), ('ZA', 'South Africa'), ('IT', 'Italy'), ('MM', 'Myanmar'), ('KR', 'South Korea'), ('CO', 'Colombia'), ('ES', 'Spain'), ('UA', 'Ukraine'), ('AR', 'Argentina')], default='CA', max_length=5)),
                ('has_work_permit', models.BooleanField(default=True)),
                ('work_permit_pr', models.FileField(upload_to='')),
                ('has_first_aid_training', models.BooleanField(default=False)),
                ('first_aid_training_certificate', models.FileField(upload_to='')),
                ('has_cpr_training', models.BooleanField(default=False)),
                ('cpr_training_certificate', models.FileField(upload_to='')),
                ('has_nanny_training', models.BooleanField(default=False)),
                ('nanny_training_certificate', models.FileField(upload_to='')),
                ('has_elderly_care_training', models.BooleanField(default=False)),
                ('elderly_care_training_certificate', models.FileField(upload_to='')),
                ('bio', models.TextField()),
                ('availability', models.ManyToManyField(to='skills.availability')),
                ('skills', models.ManyToManyField(to='skills.skills')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.days')),
                ('timeslots', models.ManyToManyField(to='skills.timeslot')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'day')},
            },
        ),
    ]
