# Generated by Django 4.2.6 on 2023-10-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_address_line_1_userprofile_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='availability',
            new_name='commitment_type',
        ),
    ]
