# Generated by Django 4.2.6 on 2023-10-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_availability_userprofile_commitment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='amount_per_hour',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
