# Generated by Django 4.2.6 on 2023-10-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_amount_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('CA', 'Canada')], default='CA', max_length=5),
        ),
    ]
