# Generated by Django 4.2.6 on 2023-10-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_1',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, choices=[('TOR', 'Toronto'), ('VAN', 'Vancouver'), ('MON', 'Montreal'), ('CAL', 'Calgary'), ('EDM', 'Edmonton'), ('OTT', 'Ottawa'), ('QUE', 'Quebec City'), ('WIN', 'Winnipeg'), ('HAL', 'Halifax'), ('VIC', 'Victoria')], max_length=100, null=True),
        ),
    ]
