# Generated by Django 4.2.6 on 2023-11-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_childcareneed_created_at_childcareneed_updated_at'),
        ('users', '0009_remove_userprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expectation',
            field=models.ManyToManyField(to='skills.expectation'),
        ),
    ]
