# Generated by Django 4.2.6 on 2023-11-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.JSONField(),
        ),
    ]
