# Generated by Django 4.2.6 on 2023-10-15 12:46

import apps.common.choices
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', verbose_name=apps.common.choices.BookingStatusChoices)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('nanny', models.ForeignKey(limit_choices_to={'role': 'Nanny'}, on_delete=django.db.models.deletion.CASCADE, related_name='nanny_bookings', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'Parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
