# Generated by Django 4.2.6 on 2023-10-15 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_childcareneed_expectation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='additional_notes',
            new_name='additional_message',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_booked',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='care_needs',
            field=models.ManyToManyField(null=True, to='skills.childcareneed'),
        ),
        migrations.AddField(
            model_name='booking',
            name='commitment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.availability'),
        ),
        migrations.AddField(
            model_name='booking',
            name='expectations',
            field=models.ManyToManyField(null=True, to='skills.expectation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nanny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nanny_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='BookingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='booking.booking')),
                ('time_slots', models.ManyToManyField(to='skills.timeslot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
