# Generated by Django 4.2.6 on 2023-10-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_childcareneed_created_at_childcareneed_updated_at'),
        ('booking', '0002_rename_additional_notes_booking_additional_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='care_needs',
            field=models.ManyToManyField(to='skills.childcareneed'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expectations',
            field=models.ManyToManyField(to='skills.skills'),
        ),
    ]
