# Generated by Django 4.2.6 on 2023-10-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_care_needs_alter_booking_expectations'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookingdate',
            constraint=models.UniqueConstraint(fields=('booking', 'date'), name='unique_booking_date'),
        ),
    ]
