# Generated by Django 4.2.6 on 2023-11-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
