# Generated by Django 4.2.6 on 2023-10-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='availability',
            field=models.CharField(choices=[('F', 'Full Time'), ('P', 'Part Time')], max_length=50, unique=True),
        ),
    ]
