# Generated by Django 4.2.6 on 2023-10-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_availability_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='name',
            field=models.CharField(choices=[('MOR', 'Morning'), ('AFT', 'Afternoon'), ('EVE', 'Evening'), ('NIG', 'Night')], max_length=50),
        ),
    ]
