# Generated by Django 4.2.6 on 2023-10-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_timeslot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCareNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('baby_care', 'Baby Care'), ('grade_school', 'Grade School'), ('teenager', 'Teenager'), ('toddler', 'Toddler')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('cooking', 'Cooking'), ('dining', 'Dining'), ('heavy_laundry', 'Heavy Laundry'), ('cleaning', 'Cleaning Entire House'), ('bathe_children', 'Bathe and Dress Children')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
