# Generated by Django 4.2.6 on 2023-10-15 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_childcareneed_expectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcareneed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 15, 15, 57, 31, 634591, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childcareneed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
