# Generated by Django 4.2.6 on 2023-11-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_childcareneed_created_at_childcareneed_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
