# Generated by Django 4.2.6 on 2023-11-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_expectation_userprofile_experience_and_more'),
        ('booking', '0004_alter_review_user'),
        ('skills', '0006_timeslot_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChildCareNeed',
            new_name='Experience',
        ),
    ]
