# Generated by Django 4.2.6 on 2023-11-19 16:28

import apps.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymentmethod_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='image',
            field=models.ImageField(upload_to='', validators=[apps.common.utils.validate_file_size]),
        ),
    ]
