# Generated by Django 4.2.6 on 2023-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymentmethod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
