# Generated by Django 4.2.6 on 2023-11-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paymentmethod_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='image',
        ),
    ]
