# Generated by Django 4.2.6 on 2023-11-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_paymentmethod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('google_pay', 'Google Pay'), ('apple_pay', 'Apple Pay'), ('cash', 'Cash')], default='credit_card', max_length=20, unique=True),
        ),
    ]
